FROM golang:1.20.1

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
WORKDIR /home
RUN git clone https://github.com/influxdata/flux.git
WORKDIR /home/flux
RUN go install github.com/influxdata/pkg-config && go mod tidy
ENV PATH="/root/.cargo/bin:${PATH}"
RUN go build ./cmd/flux

FROM ubuntu:20.04
WORKDIR /root/
COPY --from=0 /home/flux/flux .
CMD [ "./flux", "--enable-suggestions" ]